### ISSUE TITLE
Update pandana_snap_points function with improved re-projection internals

### ISSUE THREAD

**Issue by rbanick** [worldbank/GOSTnets#16]
Would it be possible to update the `pandana_snap_points` with the more efficient re-projection operations of the `pandana_snap_c` function? 

Snap_points is important for calculating origin-destination direct walking times and the current, slow function single-handedly multiplies the time it takes to generate accessibility analysis.

**Comment by d3netxer** [comment]
Looks like @andresfchamorro updated this in this commit: 68958174e8289897757fe72d6731e10d49c81618
