### ISSUE TITLE
merging Market_Access code from GOST_PublicGoods

### ISSUE THREAD

**Issue by d3netxer** [worldbank/GOSTnets#23]
It makes sense to merge the Market_Access code from GOST_PublicGoods (https://github.com/worldbank/GOST_PublicGoods/tree/master/Market_Access) to GOSTnets. I would like to gather other peoples' thoughts.

I took a look at the existing code, and here are the potential files to merge and my thoughts:

- Correcting_Missing_Points.ipynb: I'm not sure what this does. I Recommend not merging
- generate_OSRM: This code seems to deal with converting a network to a raster. I recommend not merging, but think about if any code would be useful for InfraSAP
- OSMNX_POIS: This code is useful for fetching OSM POIs via OSMNX, we just need to make sure that the functions are compatible with the latest OSMNX APIs. I Recommend merging.
- MA.py and OD.py: I believe that OD.py is a newer version of MA.py. It is a way for making OSRM calls and creating an OD matrix. I Recommend adding the Mapbox function from MA.py into OD.py, and then merging.

Can we rename the modules in GOSTNets, such as OSMNX_POIs.py --> fetch_pois.py, OD.py --> fetch_od.py ?

**Comment by d3netxer** [comment]
@bpstewar @andresfchamorro

**Comment by bpstewar** [comment]
I agree Tom, go ahead and give it a try

**Comment by d3netxer** [comment]
ok done : )

**Comment by KPGeo** [comment]
If I recall correctly, there is a difference in the calculation of MA.py and OD.py which related to the sensitivity of the MP analysis to transport costs.

**Comment by d3netxer** [comment]
I created a branch that has the old code if we want to compare here: [https://github.com/worldbank/GOST_PublicGoods/tree/old_market_access_branch/Market_Access ](https://github.com/worldbank/GOST_PublicGoods/tree/old_market_access_branch/Market_Access )

I see a lambder_list that has the different sensitivities for gravity model in both files, I'm not sure if that's what you are looking for or not.
