### ISSUE TITLE
Standardize doc-strings

### ISSUE THREAD

**Issue by elbeejay** [worldbank/GOSTnets#44]
Most functions have doc-strings but they are not consistently formatted. Making them all consistent will improve the quality of the API documentation that will inevitably be auto-generated.

**Comment by g4brielvs** [comment]
@elbeejay Thanks! This is important and would increase the usability and consistency to this package. Additionally, it goes along with [this discussion](https://github.com/orgs/worldbank/discussions/6).

**Comment by g4brielvs** [comment]
@elbeejay Let's adopt Numpy's [Style Guide](https://numpydoc.readthedocs.io/en/latest/format.html). I've added [ruff to pre-commit](https://github.com/worldbank/GOSTnets/blob/c16245b6a99765cfc00499f5be6bda495399f57f/pyproject.toml#L56).
