### ISSUE TITLE
Auto linting/styling of code

### ISSUE THREAD

**Issue by elbeejay** [worldbank/GOSTnets#45]
Add a linter and potentially a styler to automatically lint and style the code as part of the CI process when pull requests are opened and when pushes are made to 'main'.

**Comment by g4brielvs** [comment]
@elbeejay Thanks! It'd be fantastic to introduce something like [pre-commit](https://pre-commit.com). Do you have any thoughts?

**Comment by g4brielvs** [comment]
Closed by #52.
