### ISSUE TITLE
Amend missing dependencies

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/GOSTnets#49]
In current [installation](194a564075cb44adec49c63bf1f49d84bebaf6ae), dependencies are missing, e.g., `scipy` and `osmnx` and it fails.

**Comment by elbeejay** [comment]
I think they exist in the current [setup.py](https://github.com/worldbank/GOSTnets/blob/master/setup.py#L14) file, but in either case the switch to `pyproject.toml` will include all the needed dependencies there.
